### ISSUE TITLE
Images cannot be seen on branches

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#813] opened 2015-08-12 12:11 UTC
Originally reported on Google Code with ID 517

```
What steps will reproduce the problem?
1. have a Git repo with image files
2. branch it
3. navigate to the image file in the branch

What is the expected output? What do you see instead?
For the head I can see the image shown as the content of the file.
For the branch the server just sends back this string instead of the image data:

<h1>Error</h1><p>Sorry, the requested resource <strong>/documentation/docs/images/blah.png</strong>
was not found in <strong>johndoe/documentation</strong>.</p>

What version of the product are you using? On what operating system?
1.6.1 on Win7

```

Reported by `bpalyi` on 2014-10-22 18:13:58

**Comment by fzs** [comment] 2016-12-14 19:33
@bpalyi, any update on this?

**Comment by flaix** [comment] 2020-11-09 21:08
The key here is that the branch name used was `johndoe/documentation`, which has a forward slash in it. Thus this is the problem of loading raw files from branches with a slash. 
I am setting this as a duplicate of #1290, because that ticket has a better explanation in the report, unlike this one, even if this one was reported earlier.

**Closed** 2020-11-09 22:27 UTC
Labels: Catg-Defect, Status-Duplicate
