### ISSUE TITLE
Web editing

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#635] opened 2015-08-12 12:01 UTC
Originally reported on Google Code with ID 339

```
Hi,

First off, I must say I'm really pleased with Gitblit, this is the most versatile Git
server I could find (and I've been looking for quite some time), so kudos and keep
up the good job, guys.

Now this ticket is a feature request. There are cases when allowing web editing would
be really, really useful. E.g. we are developing our own websites and there are novice
users from PR who aren't really into SCM (i.e. they are completely clueless) but from
time to time they need/want to update text on the sites. Teaching them how to use Git
would be really a challenge and is probably not a good idea because sooner or later
they'd probably break something unintentionally (sometimes even devs do, it's not too
hard with Git:). This is just one example, but there are lots of scenarios when this
can be really nice, I think there's no doubt about it.

So what I propose is pretty much the same what GitHub offers. I attach a screenshot,
I think it's self-explanatory.

What do you think?
```

Reported by `sundayfunday1234@outlook.com` on 2013-11-18 09:53:01

-----
- _Attachment: webedit.png<br>![webedit.png](https://storage.googleapis.com/google-code-attachments/gitblit/issue-339/comment-0/webedit.png)_
_Edit: Make image render_

**Comment by yurgisbaykshtis** [comment] 2015-10-09 19:26
Plus that. Plain text editing support (without even syntax highlight) as a first iteration would be very very handy.

**Comment by yurgis2** [comment] 2015-10-09 19:27
Plus that. Plain text editing support (without even syntax highlight) as a first iteration would be very very handy.

**Comment by fzs** [comment] 2016-12-17 21:26
Closing as a duplicate of #974 since #974 is more active and includes already commits.

**Closed by fzs** 2016-12-17 21:26 UTC
Labels: Status-Duplicate, Type-Feature
