### ISSUE TITLE
Permissions per ref

### ISSUE THREAD

**Issue by bjarteskogoy** [gitblit/gitblit#911] opened 2015-08-28 08:48 UTC
It would be great to be able to control permissions per ref.

**Comment by gitblit** [comment] 2015-09-01 12:35
Hi @bjarteskogoy. That would be a nice improvement.  This could be implemented now as a Groovy hook script[1][2] or as a plugin[3]. The original discussion concerning ref permissions was imported as issue #332.

I don't expect to be working on this anytime soon.  If you want to submit a PR I'll be happy to review it.

- [1]: https://github.com/gitblit/gitblit/blob/master/src/main/distrib/data/groovy/protect-refs.groovy
- [2]: https://github.com/gitblit/gitblit/blob/master/src/main/distrib/data/groovy/blockpush.groovy
- [3]: https://github.com/gitblit/gitblit-tbacl-plugin

**Comment by fzs** [comment] 2016-12-17 21:53
Closing this as a duplicate of #332. While #332 is a rather broad request, repository level permissions have been implemented to branch/tag permissions are what is left.

**Closed by fzs** 2016-12-17 21:53 UTC
Labels: Status-Duplicate, Type-Feature
