### ISSUE TITLE
Raw Links Don't Work When A Group Shares Name With Repository

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#879] opened 2015-08-12 12:13 UTC
Originally reported on Google Code with ID 583

```
What steps will reproduce the problem?
1. Create Repository Company/Software/Android.git
2. Create Repository Company/Software/Android/MyApp.git
3. Create file somefile.txt in MyApp repository.
3. Navigate to MyApp repository and go to the tree view.
4. Click on *raw* for somefile.txt
    - Your Browser navigates to https://myserver/raw/Company/Software/Android/MyApp.git/master/somefile.txt
    - Error Sorry, the repository Company/Software/Android does not have a MyApp.git
branch!


What version of the product are you using? On what operating system?
1.6.2

Please provide any additional information below.
View links work OK but they escape the slashes in the repository name such the view
link would be:

https://myserver/blob/Company%2FSoftware%2FAndroid%2FMyApp.git/master/somefile.txt

If I try escaping the repo name in the raw url, i get the same error: Sorry, the repository
Company/Software/Android does not have a MyApp.git branch!

```

Reported by `jonathan@jacksonengineering.net` on 2015-04-15 19:50:54

**Comment by flaix** [comment] 2020-11-09 22:02
I cannot reproduce this with 1.9.1, and the current code does not suggest any problems with such a setup.
This was most probably fixed with commit 2b1e02997f, which is part of version 1.8.0.
So I am assigning this to version 1.8.0, setting it to fixed.

**Closed** 2020-11-09 22:02 UTC
Labels: Catg-Defect, Status-Fixed
