### ISSUE TITLE
Support for signed commits

### ISSUE THREAD

**Issue by sanel** [gitblit/gitblit#1068] opened 2016-04-26 16:35 UTC
Recently github added [support for signed commits with GPG](https://help.github.com/articles/signing-commits-using-gpg/), visually displaying when commit is signed and verified.

I moved couple of github repos with a many signed commits to private giblit server; however, there is no indication when commit is signed or signature verified. Is there any option this could be added and how hard is to do so?

Thanks!

**Comment by gitblit** [comment] 2016-04-26 20:10
This has been discussed before - maybe on the mailing list or in a GoogleCode issue.  I have no idea how complex it would be.  I'm pretty sure it would require shelling out to GPG and relying on a proper GPG installation which doesn't exactly fit into *pure Java git solution*.  Easier to handle this on a *nix box than on a Windows box too.

**Comment by sanel** [comment] 2016-04-27 08:15
Couple of options/proposals:

1. shelling could be a viable option: at startup check `gpg` command or use path from `gitblit.properties`, mainly for Windows, since gpg can be installed via [Gpg4Win](http://gpg4win.org) - seems simple? If not present, no bad feelings

2. use bouncycastle - [some examples](https://github.com/weiliatgithub/bouncycastle-gpg-example) for pure Java solution. Will this require Java 8?

**Comment by gitblit** [comment] 2016-04-27 11:50
Nice.  I didn't realize BouncyCastle supported GPG.  Gitblit already ships with it so that would be where I would start.

**Comment by fzs** [comment] 2016-12-17 22:47
Closing as duplicate of #634.

**Closed by fzs** 2016-12-17 22:47 UTC
Labels: Status-Duplicate, Type-Feature
