### ISSUE TITLE
Missing content error in raw view & treeview

### ISSUE THREAD

**Issue by exxdevop** [gitblit/gitblit#1234] opened 2017-05-18 14:29 UTC
Hello GitlBlit-Team,

we got a problem with the raw view of GitBlit. First things first, some details about our setup:

- GitBlit version 1.8.0 (JAR)
- JAVA 1.8

The service runs behind an apache 2.4 webserver with reverse proxy configuration like this:
```
        ProxyRequests Off
        ProxyVia Off
        ProxyPreserveHost On
        <Proxy>
              AddDefaultCharset off
              Require all granted
        </Proxy>
        ProxyPass / http://127.0.0.1:5010/
        ProxyPassReverse / http://127.0.0.1:5010/
```
We also set the option `web.forwardSlashCharacter` in the `gitblit.properties` to `!` to prevent problems with encoded slashes.

The actual problem occures when browsing a branch (with a slash in its name) of a repository with the treeview and from there showing a specific file in raw view. The service runs into an error that the resource could not be found.

To reproduce the error, we:

1. create a repository
2. check out locally with git
3. create a branch ( e.g. foo/bar-123)
4. create a dummy file in this branch
5. commit & push 
6. open the gitblit webpage
7. browse to repo
8. select branch from list
9. change to tree view
10. select raw link on file to switch to raw view

At this point the error occurs.

Thanks for advice and kind regards

**Comment by tjuchniewicz** [comment] 2018-01-18 09:07
Any workaround available?

**Comment by yuri1969** [comment] 2018-04-05 09:02
This issue indirectly affects all the markdown display (think of a `README.md`) which links an external content (think of a bitmap image).

**Comment by flaix** [comment] 2020-11-09 21:15
The branch is not just e.g. `foo/bar-123`, but it is essential to the problem that it is a branch with a slash in the name.
The raw display is broken for branches with a slash in the name. This is a duplicate of #1290, or the other way around, however you wanna see it. But #1290 has the better description mentioning the fact about the slash in the branch name.

**Closed** 2020-11-09 22:29 UTC
Labels: Catg-Defect, Status-Duplicate
