### ISSUE TITLE
404 missing index.jsp from gitblit war file and java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by BullShark** [gitblit/gitblit#1330] opened 2020-02-09 07:22 UTC
Hello. I am a noob at Apache Tomcat. I downloaded gitblit-1.8.0.war from http://gitblit.com/ . I renamed it to gitblit.war and placed it under /usr/share/tomcat/webapps on my server. I then tried to load http://mydomain.com:8080/gitblit in my browser, and I get a blank page. I checked the logs, and there are 404 errors. I've never had this happen before. I checked the war file. It doesn't contain an index.jsp file. 

I have several log files for Apache Tomcat.

localhost.2020-02-09.log
http://vpaste.net/J0DH0

catalina.2020-02-09.log
http://vpaste.net/47B7T

Another log file:

`
10.8.0.4 - - [09/Feb/2020:00:12:52 -0600] "GET /gitblit/ HTT
P/1.1" 404 -
10.8.0.4 - - [09/Feb/2020:00:24:30 -0600] "GET /favicon.ico
HTTP/1.1" 404 -
10.8.0.4 - - [09/Feb/2020:01:25:53 -0600] "GET /favicon.ico
HTTP/1.1" 404 -
10.8.0.4 - - [09/Feb/2020:01:25:56 -0600] "GET /gitblit/ HTT
P/1.1" 404 -
2a00:1098:84:1c8:0:0:0:157 - - [09/Feb/2020:01:29:46 -0600]
"GET /gitblit HTTP/1.1" 404 -
`

**Comment by fzs** [comment] 2020-02-10 22:13
Hi!

I haven't found the time to investigate more, but I take it you are running this with Java 11?
Can you download the newest [version 1.9.0](https://github.com/gitblit/gitblit/releases/tag/v1.9.0) and try with that, first?

Thanks.

**Comment by BullShark** [comment] 2020-02-16 16:37
Sorry. I uninstalled Tomcat and Gitblit in favor of running Gitea on my server. I'll make another report for the Gitblit irc hook I wrote in Groovy a while back, and hopefully it will be included with Gitblit.

**Comment by BullShark** [comment] 2020-02-16 16:44
My Java version.

[bull@odin ~]$ java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment 19.9 (build 13.0.2+8)
OpenJDK 64-Bit Server VM 19.9 (build 13.0.2+8, mixed mode, sharing)
[bull@odin ~]$ javac -version
javac 13.0.2
[bull@odin ~]$ rpm -qa | grep -E 'java|jdk'
copy-jdk-configs-3.3-10.el7_5.noarch
java-latest-openjdk-headless-13.0.2.8-1.rolling.el7.x86_64
java-latest-openjdk-devel-13.0.2.8-1.rolling.el7.x86_64
javapackages-tools-3.4.1-11.el7.noarch
java-latest-openjdk-13.0.2.8-1.rolling.el7.x86_64
java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64
tzdata-java-2019c-1.el7.noarch
java-1.8.0-openjdk-devel-1.8.0.242.b08-0.el7_7.x86_64
python-javapackages-3.4.1-11.el7.noarch
java-1.8.0-openjdk-headless-1.8.0.242.b08-0.el7_7.x86_64
[bull@odin ~]$

**Comment by fzs** [comment] 2020-02-16 20:17
I am closing this a fixed, then, as the ClassNotFound error was a bug when running in Tomcat with Java 11+ and is fixed in version 1.9.0. I could not reproduce this with 1.9.0.

**Closed by fzs** 2020-02-16 20:17 UTC
Labels: Catg-Defect, Status-Fixed
