### ISSUE TITLE
RAW servlet has issues when there is a Git repo and a group with the same name

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#848] opened 2015-08-12 12:12 UTC
Originally reported on Google Code with ID 552

```
What steps will reproduce the problem?
1. Create a repo named test.git
2. Create a repo test/sub.git
3. Try to view a file with the RAW servlet on test/sub.git

What is the expected output? What do you see instead?
I expect to see the file, instead I get an error that the branch sub.git doesn't exist
in the test.git repo

What version of the product are you using? On what operating system?
1.6.2

Please provide any additional information below.
Maybe the RAW servlet should check the repo against the longest match
```

Reported by `Sascha.Vogt` on 2015-01-27 10:11:22

**Comment by fzs** [comment] 2016-12-17 20:56
Duplicate of #879

**Closed by fzs** 2016-12-17 20:56 UTC
Labels: Priority-Medium, Status-Duplicate, Type-Defect
