### ISSUE TITLE
Gitblit ignores transport preference

### ISSUE THREAD

**Issue by bviktor** [gitblit/gitblit#1102] opened 2016-07-25 17:15 UTC
Steps to reproduce:

```
git.acceptedPushTransports = HTTP HTTPS SSH
git.sshBindInterface =
git.sshPort = 29418
git.daemonBindInterface = localhost
git.daemonPort = 9418
```

Set your transport preference to `HTTP` (default).

Now navigate to a repo and it will offer the ssh:// URL by default.

Gitblit 1.8.0.

**Comment by flaix** [comment] 2020-10-29 20:51
I cannot reproduce this. When trying it out, the preferred transport was offered as the preferred URL on the repository page.

Note, however, that Gitblit will use the received browser request to form a HTTP/HTTPS URL. What this means is, that when you access Gitblit with your browser with HTTP, then a HTTP URL will be shown in the repository URL drop down, but no HTTPS. And if you access Gitblit with HTTPS, then only the HTTPS URL will be available as a repository URL on the repository page, not a HTTP one.

So what can have happened is, that you set HTTP as the preferred transport for the user, but then used HTTPS to access the Gitblit repo page. Which will lead to no HTTP URL being amongst the repo URL list. Then Gitblit will choose the most secure one, which is SSH. Would you have accessed Gitblit with HTTP, then you would have seen the HTTP URL as the preferred one.

Gitblit works this way because in the HTTP/HTTPS case it will have to take reverse proxies, web containers, etc. into account to form a working URL.

I'm closing this as Cannot Reproduce. Should you still have the same problem, and it is not based on above behaviour, then please re-open with more information on how to reproduce it: logs, environment, client, whatever might help.

**Closed by flaix** 2020-10-29 20:51 UTC
Labels: Catg-Defect, Status-CanNotReproduce
