### ISSUE TITLE
nginx show error Can not load repository software for admin

### ISSUE THREAD

**Issue by laynezhang** [gitblit/gitblit#1310] opened 2019-05-16 06:24 UTC
nginx(server_name github.water.com) proxy to 127.0.0.1:10080
browser http://git.water.com/
create project    software/myproject.git
click repositories  click myproject   
show error Can not load repository software for admin
click edit

2019-05-16 05:34:17 [INFO ] Found more URL path parts then expected, these will be ignored. Url: 'http://127.0.0.1:10080/edit/software/myproject.git', mountpath: 'edit', urlPath: 'software/myproject.git', expected 1 parameters was 2
2019-05-16 05:34:17 [ERROR] Can't instantiate page using constructor public com.gitblit.wicket.pages.EditRepositoryPage(org.apache.wicket.PageParameters) and argument r = "software"
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public com.gitblit.wicket.pages.EditRepositoryPage(org.apache.wicket.PageParameters) and argument r = "software"
	at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
	at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)

**Comment by fzs** [comment] 2019-05-20 07:58
I don't know how to reproduce this. I have Gitblit behind a nginx reverse proxy and it works, also with repositories in deeper levels of directories.
Have a look at the link that is set for the "edit" button, what does it look like?
What are web.mountParameters, web.forwardSlashCharacter and server.contextPath set to?

**Comment by laynezhang** [comment] 2019-05-21 02:41
my config file:(install 1.8.0 defaults.properties )
I modified it 
server.httpPort = 10080

others parameters:
web.mountParameters = true

**Comment by laynezhang** [comment] 2019-05-21 02:56
but I browser
http://127.0.0.1:10080 
click  repositories --  myproject(http://127.0.0.1:10080/summary/software%2Fmyproject.git)   -- edit(http://127.0.0.1:10080/edit/software%2Fmyproject.git)
everything is normal
my nginx version 1.14.2
my os ubuntu 18.04.2 LTS
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by laynezhang** [comment] 2019-05-21 02:58
nginx server.conf
server {
    listen  80;
    server_name git.water.com;

    root    /var/www;

    location / {
        proxy_http_version  1.1;
        proxy_pass    http://127.0.0.1:10080/;
            
        client_max_body_size 512M;
        
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}

**Comment by fzs** [comment] 2019-05-21 09:33
Hm, I do have it working with that configuration, so there is no principle error.
It looks like in the proxied case in the URL that reaches Gitblit the %2F is replaced with an actual slash. Thus Gitblit will find more than one mount parameter, ignoring the repository name and using the path part "software" as the repository name. Which it doesn't find of course.

I don't know why this works in my setup but not in yours. What you can do is play around with the web.forwardSlashCharacter or turn off web.mountParameters.

http://gitblit.com/setup_proxy.html

**Comment by laynezhang** [comment] 2019-05-22 00:41
Thank you very much

**Comment by fzs** [comment] 2019-05-26 12:37
Did this solve your problem? If yes, you can close this issue.

**Closed** 2019-10-10 14:47 UTC
