### ISSUE TITLE
gitblit does not show branch graph when behind revert proxy

### ISSUE THREAD

**Issue by scsi** [gitblit/gitblit#1175] opened 2017-01-05 00:34 UTC
I use apache to proxy gitblit and gitblit branch graph does not show

my proxy setting is reference form http://gitblit.com/setup.html 
proxy setting is:

> AllowEncodedSlashes On
> ProxyRequests Off
> ProxyVia Off
> ProxyPreserveHost On
> <Proxy *>
>         AddDefaultCharset off
>         Order deny,allow
>         Allow from all
>  </Proxy 　>
> ProxyPass /gitblit http://localhost:8080/gitblit
> ProxyPassreverse /gitblit http://localhost:8080/gitblit
> 

I try to add " nocanon" to tail of ProxyPass, but It is not work
Can anybody help me ><~
Thx.....

**Comment by fzs** [comment] 2017-01-06 08:04
This is a duplicate of #855, I believe.

**Closed by fzs** 2017-01-06 08:04 UTC
Labels: Status-Duplicate, Type-Defect
