### ISSUE TITLE
When changing the access policy of a projet I got an NPE

### ISSUE THREAD

**Issue by fbacchella** [gitblit/gitblit#1097] opened 2016-07-05 15:12 UTC
The stack trace is:

```
2016-07-05 17:04:03 ERROR org.apache.wicket.RequestCycle : 
java.lang.NullPointerException
        at com.gitblit.wicket.panels.AccessPolicyPanel.updateModel(AccessPolicyPanel.java:163)
        at com.gitblit.wicket.pages.EditRepositoryPage$3.onUpdate(EditRepositoryPage.java:628)
        at org.apache.wicket.ajax.form.AjaxFormChoiceComponentUpdatingBehavior.respond(AjaxFormChoiceComponentUpdatingBehavior.java:179)
        at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:312)
        at org.apache.wicket.request.target.component.listener.BehaviorRequestTarget.processEvents(BehaviorRequestTarget.java:157)
        at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
        at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)
        at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)
        at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)
        at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
        at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.EnforceAuthenticationFilter.doFilter(EnforceAuthenticationFilter.java:99)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.gitblit.servlet.ProxyFilter$1.doFilter(ProxyFilter.java:89)
        at com.gitblit.servlet.ProxyFilter.doFilter(ProxyFilter.java:82)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:88)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.jasig.cas.client.tomcat.v7.CleanCas20CasAuthenticator.invoke(CleanCas20CasAuthenticator.java:43)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by paulsputer** [comment] 2016-07-05 17:46
Thanks for reporting @fbacchella couple of questions:
1. Are you using the latest 1.8.0 version of GitBlit?
2. What was the initial policy value and what were you changing?

**Comment by fbacchella** [comment] 2016-07-06 15:04
1. Yes, I just upgraded it.
2. I was switching from "Restrict View, Clone, & Push" to "Restrict Clone & Push"

**Comment by flaix** [comment] 2020-10-29 21:31
I am closing this as CannotReproduce.

I tried and could not reproduce the exception with the described steps. Just from looking at the code, I have no idea how that value could be null. Since there are no other comments or votes on the issue, I assume this was a one time freak event. If this happens again, please re-open.

**Closed by flaix** 2020-10-29 21:31 UTC
Labels: Catg-Defect, Status-CanNotReproduce
